---
# This collection is initialized by https://github.com/ansible/ansible-creator 26.6.1

# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: "adfinis"
name: "icinga2"
version: 1.0.0
readme: README.md
authors:
  - Adfinis <https://adfinis.com>

description: Install and configure Icinga 2 (agent, client, master) and Icinga Web 2
license_file: LICENSE

tags: ["icinga2", "monitoring", "icingaweb2", "linux"]
dependencies:
  "ansible.posix": ">=1.0.0"
  "community.general": ">=1.0.0"
  "community.mysql": ">=1.0.0"

repository: https://github.com/adfinis/ansible-collection-icinga2
documentation: https://github.com/adfinis/ansible-collection-icinga2/blob/main/README.md
homepage: https://github.com/adfinis/ansible-collection-icinga2
issues: https://github.com/adfinis/ansible-collection-icinga2/issues

# A list of file glob-like patterns used to filter any files or directories that should not be included in the build
# artifact. A pattern is matched from the relative path of the file or directory of the collection directory. This
# uses 'fnmatch' to match the files or directories. Some directories and files like 'galaxy.yml', '*.pyc', '*.retry',
# and '.git' are always filtered. Mutually exclusive with 'manifest'
build_ignore:
  - .gitignore
  - .ansible
  - changelogs/.plugin-cache.yaml
# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null
