---
driver:
  name: default

platforms:
  - name: icinga2-parent
    image: "docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    groups:
      - masters

  - name: icinga2-client
    image: "docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    groups:
      - clients

provisioner:
  name: ansible
  playbooks:
    create: ../utils/playbooks/create.yml
    destroy: ../utils/playbooks/destroy.yml
  inventory:
    group_vars:
      all:
        ansible_connection: containers.podman.podman

scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
